export { default as CourseCard } from "./card"
export { default as CourseList } from "./list"
export { default as CourseHero } from "./hero"
export { default as CourseBody } from "./body"
export { default as CourseCurriculum } from "./curriculum"